{% set version = "1.2.2-1" %}
{% set sha256 = "928aa91623553711b5e51dafc1271717e7d69ad0bd202a42309100c25721d53a" %}

package:
  name: ros-environment
  version: {{ version.split("-")[0] }}

source:
  url: https://github.com/ros-gbp/ros_environment-release/archive/release/melodic/ros_environment/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - python
    - catkin_pkg
    - ros-catkin
  run:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - python

test:
  requires:
    - rospkg
  commands:
    - export ROS_ROOT=$PREFIX && python -c "import rospkg;s = rospkg.RosPack();ret = s.get_path('ros_environment');print(ret)"

about:
  home: https://github.com/ros/ros_environment
  summary: |
    The package provides ROS environment variables.
  description: |
    The package provides the environment variables `ROS_VERSION`, `ROS_DISTRO`,
    `ROS_PACKAGE_PATH`, and `ROS_ETC_DIR`.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
